import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/Providers/AuthProvider";
import Toast from "@/lib/Providers/Toast";

const inter = Inter({
  weight: ["100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <Toast>
            <main className="p-10">{children}</main>
          </Toast>
        </body>
      </html>
    </AuthProvider>
  );
}
